services:
  # PostgreSQL Database
  db:
    image: postgres:13-trixie # latest stable version as of 2025-09
    container_name: code_review_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: code_review
    ports:
      # Conflicting with local Postgres installations, so we map to 5433
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis (Message Broker + Cache)
  redis:
    image: redis:latest # reccomended by official docker hub page
    container_name: code_review_redis
    ports:
      - "6379:6379"

  # FastAPI Web Application
  web:
    build: .
    container_name: code_review_web
    command: /app/.venv/bin/uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # This mount enables hot reloading for your application code
      - .:/app
      # This mount masks the host's .venv from overwriting the container's .venv
      - /app/.venv
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/code_review
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # Celery Worker (will be added later)
  # worker:
  #   build: .
  #   container_name: code_review_worker
  #   command: celery -A app.tasks.celery_app worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   env_file: .env
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/code_review
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data:
